### ISSUE TITLE
src/duoshuo.js 的 initSelector 参数传递错误

### ISSUE THREAD

**Issue by zsxsoft** [duoshuo/angular-duoshuo#2]
![qq 20150202123021](https://cloud.githubusercontent.com/assets/2398785/5995820/58dc2984-aad7-11e4-9b54-8fe735f193aa.png)
![qq 20150202123051](https://cloud.githubusercontent.com/assets/2398785/5995821/591977ee-aad7-11e4-8b43-abf95a1f062f.png)
![qq 20150202123204](https://cloud.githubusercontent.com/assets/2398785/5995827/82330956-aad7-11e4-9ed6-b6beb890f06e.png)

根据代码判断，是否应该改为
 window.DUOSHUO.initSelector('.' + type, window.DUOSHUO.selectors['.' + type])
以让选择器选择到class="{{type}}"呢？

**Comment by guo-yu** [comment]
这个硬编码问题已经在 `v0.5.2` 版本中解决了，非常感谢！
